import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/contexts/AuthContext'

type Crew={id:string;name:string;region:string}
type Proposal={id:string;name:string;status:string;projects:{id:string;name:string;status:string}}
type Assignment={id:string;proposal_id:string;crew_id:string;work_date:string;planned_hours:number|null;field_notes:string;status:string;version:number}
const input='block w-full rounded border border-brand-border bg-white p-3 mt-1'
const button='rounded bg-brand-navy px-4 py-3 text-white disabled:opacity-50'
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export default function CrewSchedule(){
 const {user}=useAuth(),[params]=useSearchParams()
 const [crews,setCrews]=useState<Crew[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[rows,setRows]=useState<Assignment[]>([])
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const [crewName,setCrewName]=useState(''),[region,setRegion]=useState('Cape Cod')
 const [edit,setEdit]=useState<Assignment|null>(null),[proposal,setProposal]=useState(params.get('proposal')??''),[crew,setCrew]=useState(''),[date,setDate]=useState(today()),[hours,setHours]=useState(''),[notes,setNotes]=useState(''),[status,setStatus]=useState('scheduled')
 const [from,setFrom]=useState(today()),[filterCrew,setFilterCrew]=useState(''),[showCancelled,setShowCancelled]=useState(false)
 async function load(){if(!user)return;const results=await Promise.all([supabase.from('construction_crews').select('*').eq('user_id',user.id).order('name'),supabase.from('proposals').select('id,name,status,projects!inner(id,name,status)').eq('projects.user_id',user.id),supabase.from('construction_schedule').select('*').eq('user_id',user.id).order('work_date')]);const problem=results.find(r=>r.error)?.error;if(problem)throw Error(problem.message);setCrews(results[0].data as Crew[]);setProposals(results[1].data as unknown as Proposal[]);setRows(results[2].data as Assignment[])}
 useEffect(()=>{let active=true;void load().catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)})
 // Reload when the signed-in owner changes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[user?.id])
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice('Saved.')}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.')}finally{setBusy(false)}}
 function reset(){setEdit(null);setProposal('');setHours('');setNotes('');setStatus('scheduled')}
 const eligible=proposals.filter(p=>p.status==='approved'&&p.projects.status!=='archived')
 const conflicts=rows.filter(r=>r.id!==edit?.id&&r.crew_id===crew&&r.work_date===date&&!['cancelled','done'].includes(r.status))
 return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Crew Schedule</h1><p className="mt-2">Assign approved construction work orders to a crew and work date.</p><p className="mt-2 text-brand-text-muted">This is your office plan. To make a job available on the crew’s phone, also assign it in <a className="underline" href="https://crewclaw.netlify.app/setup.html" target="_blank" rel="noreferrer">CrewClaw</a>.</p></header>
 {error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {loading?<p>Loading schedule…</p>:<>
 <details className="rounded border border-brand-border bg-white p-4" open={!crews.length}><summary className="cursor-pointer font-bold">Construction crews ({crews.length})</summary><ul className="my-3">{crews.map(c=><li key={c.id}>{c.name} · {c.region}</li>)}</ul><form className="grid gap-3 sm:grid-cols-3" onSubmit={e=>{e.preventDefault();void perform(async()=>{const {error}=await supabase.from('construction_crews').insert({user_id:user!.id,name:crewName.trim(),region});if(error)throw error;setCrewName('')})}}><label>Crew name<input className={input} value={crewName} onChange={e=>setCrewName(e.target.value)} required maxLength={150}/></label><label>Region<select className={input} value={region} onChange={e=>setRegion(e.target.value)}>{['Cape Cod','Nantucket','Metro Boston'].map(x=><option key={x}>{x}</option>)}</select></label><button className={button} disabled={busy||!crewName.trim()}>Add construction crew</button></form></details>
 <section className="rounded border border-brand-border bg-white p-4"><h2 className="text-xl font-bold">{edit?'Edit assignment':'Schedule a work order'}</h2>{!eligible.length&&<p className="my-3">No approved proposals are available to schedule. <Link className="underline" to="/app/work-orders">Review work orders</Link></p>}<form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void perform(async()=>{const payload={proposal_id:proposal,crew_id:crew,work_date:date,planned_hours:hours===''?null:Number(hours),field_notes:notes,status};const request=edit?supabase.from('construction_schedule').update({...payload,version:edit.version}).eq('id',edit.id).eq('version',edit.version):supabase.from('construction_schedule').insert({...payload,user_id:user!.id});const {data,error}=await request.select('id').single();if(error||!data)throw Error(error?.message??'Schedule changed. Refresh before saving.');reset()})}}>
 <label>Approved work order<select className={input} required value={proposal} onChange={e=>setProposal(e.target.value)}><option value="">Choose a work order</option>{proposals.filter(p=>eligible.includes(p)||p.id===edit?.proposal_id).map(p=><option value={p.id} key={p.id}>{p.projects.name} — {p.name}{p.status!=='approved'?' (no longer approved)':''}</option>)}</select></label>
 <label>Construction crew<select className={input} required value={crew} onChange={e=>setCrew(e.target.value)}><option value="">Choose a crew</option>{crews.map(c=><option key={c.id} value={c.id}>{c.name} · {c.region}</option>)}</select></label>
 <label>Work date<input className={input} type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Planned labor hours (all workers combined)<input className={input} type="number" min="0" max="10000" step="0.01" value={hours} onChange={e=>setHours(e.target.value)} placeholder="Optional"/></label>
 <label className="sm:col-span-2">Field notes<textarea className={input} maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Access, staging, work planned for this date…"/></label>
 <label>Assignment status<select className={input} value={status} onChange={e=>setStatus(e.target.value)}>{['scheduled','ongoing','done','cancelled'].map(s=><option key={s} value={s}>{s}</option>)}</select></label>
 {conflicts.length>0&&<p role="status" className="rounded bg-amber-50 p-3">This crew already has {conflicts.length} other assignment(s) on this date. Check that the crew can cover both before saving.</p>}
 <div className="flex flex-wrap gap-3"><button className={button} disabled={busy||!crews.length||(!eligible.length&&!edit)}>{busy?'Saving…':edit?'Save changes':'Schedule work order'}</button>{edit&&<button type="button" className="underline" onClick={reset} disabled={busy}>Stop editing</button>}</div></form></section>
 <section><h2 className="text-xl font-bold">Scheduled work</h2><div className="my-3 flex flex-wrap gap-4"><label>From date<input className={input} type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Filter crew<select className={input} value={filterCrew} onChange={e=>setFilterCrew(e.target.value)}><option value="">All crews</option>{crews.map(c=><option key={c.id} value={c.id}>{c.name} · {c.region}</option>)}</select></label><label className="self-center"><input type="checkbox" checked={showCancelled} onChange={e=>setShowCancelled(e.target.checked)}/> Include cancelled</label></div>
 {rows.filter(r=>(!from||r.work_date>=from)&&(!filterCrew||r.crew_id===filterCrew)&&(showCancelled||r.status!=='cancelled')).map(r=>{const p=proposals.find(p=>p.id===r.proposal_id),c=crews.find(c=>c.id===r.crew_id);return <article className="my-3 rounded border border-brand-border bg-white p-4" key={r.id}><h3 className="font-bold">{r.work_date} · {c?.name} · {c?.region}</h3><p>{p?.projects.name} — {p?.name}</p><p>{r.status} · {r.planned_hours===null?'Hours not set':`${r.planned_hours} planned labor hours`}</p><p className="my-2 whitespace-pre-wrap">{r.field_notes}</p><div className="flex flex-wrap gap-4"><button type="button" className="underline" disabled={busy} onClick={()=>{setEdit(r);setProposal(r.proposal_id);setCrew(r.crew_id);setDate(r.work_date);setHours(r.planned_hours===null?'':String(r.planned_hours));setNotes(r.field_notes);setStatus(r.status);window.scrollTo({top:0,behavior:'smooth'})}}>Edit / reschedule</button>{p&&<Link className="underline" to={`/app/projects/${p.projects.id}/proposals/${p.id}/print?format=crew`}>Open crew planner</Link>}</div></article>})}
 {!rows.some(r=>(!from||r.work_date>=from)&&(!filterCrew||r.crew_id===filterCrew)&&(showCancelled||r.status!=='cancelled'))&&<p>No assignments match these filters.</p>}</section></>}
 </div>
}
