import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {supabase} from '@/lib/supabase'
import {formatUSD,roundMoney} from '@/lib/money'
import {categories,reportProject,reportCsv,type ReportData} from '@/lib/jobReports'
const empty:ReportData={projects:[],proposals:[],areas:[],lines:[],costs:[],reviews:[]}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const names={labor:'Labor',material:'Materials',equipment:'Equipment',subcontractor:'Subcontractors',other:'Other'}
const field='block rounded border border-brand-border bg-white p-2 mt-1'
async function readAll(table:string,selection:string){const rows:unknown[]=[];for(let page=0;page<200;page++){const {data,error}=await supabase.from(table).select(selection).order('id').range(page*500,page*500+499);if(error)throw Error(`${table}: ${error.message}`);rows.push(...(data??[]));if((data?.length??0)<500)return rows}throw Error('Report exceeds 100,000 rows. Narrow the report at the data source.')}
export default function JobReports(){
 const [data,setData]=useState<ReportData>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[asOf,setAsOf]=useState(today()),[project,setProject]=useState(''),[view,setView]=useState('budget'),[baselines,setBaselines]=useState<Record<string,string>>({}),[archived,setArchived]=useState(false)
 useEffect(()=>{let cancelled=false;void Promise.all([readAll('projects','id,name,status'),readAll('proposals','id,project_id,name,status,updated_at'),readAll('proposal_work_areas','id,proposal_id,enabled,name_override,work_areas(name)'),readAll('proposal_lines','id,proposal_id,proposal_work_area_id,category,unit,quantity,frozen_unit_cost,frozen_markup_percent,price_override'),readAll('job_costs','id,project_id,category,amount,txn_date,description,account_name,vendor_name'),readAll('crewclaw_work_reviews','id,project_id,work_date,status,total_seconds,extras,materials')]).then(([projects,proposals,areas,lines,costs,reviews])=>{if(!cancelled)setData({projects,proposals,areas,lines,costs,reviews} as ReportData)}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[])
 const reports=useMemo(()=>data.projects.filter(p=>(archived||p.status!=='archived')&&(!project||p.id===project)).map(p=>reportProject(data,p,asOf,baselines[p.id])).sort((a,b)=>a.project.name.localeCompare(b.project.name)),[data,archived,project,asOf,baselines])
 const unassigned=data.costs.filter(c=>!c.project_id&&c.txn_date<=asOf)
 const flags=(r:ReturnType<typeof reportProject>)=>[!r.proposal?'No proposal budget':r.provisional?'Provisional proposal budget':null,r.multipleApproved?'Multiple approved proposals: verify baseline':null,!r.costCount?'No actual dollar costs recorded':null,r.costCount&&r.proposal&&r.actualTotal>r.budgetTotal?'Recorded costs exceed budget':null,r.hourRecordCount&&r.budgetHours>0&&r.actualHours>r.budgetHours?'Posted labor hours exceed budget':null,r.nonHourLabor?'Some labor units cannot be compared as hours':null,r.unscopedLines?'Legacy lines lack work-area mapping and are excluded':null,r.pending?`${r.pending} field records awaiting review`:null,r.extras?`${r.extras} posted extras to review for pricing`:null,r.materials?`${r.materials} posted material entries: verify corresponding costs`:null].filter(Boolean)
 function download(){const csv=reportCsv([['Project','Status','Budget proposal','Budget status','Actuals through','Estimated cost basis','Recorded actual cost','Budget remaining','Estimated labor hours','Posted labor hours','Notes'],...reports.map(r=>[r.project.name,r.project.status,r.proposal?.name??'',r.proposal?.status??'',asOf,r.proposal?r.budgetTotal:null,r.costCount?r.actualTotal:null,r.proposal&&r.costCount?roundMoney(r.budgetTotal-r.actualTotal):null,r.budgetHours,r.hourRecordCount?r.actualHours:null,flags(r).join('; ')])]);const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`bidclaw-job-report-${asOf}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const cell=(text:string|number)=> <td className="border-t border-brand-border p-3 align-top">{text}</td>
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Job Reports</h1><p className="mt-2">Budget versus recorded costs, labor usage and items needing review.</p></header>
 <div className="rounded border border-amber-200 bg-amber-50 p-4 text-sm space-y-2"><p>Budgets use the selected proposal’s enabled work areas and frozen pre-markup amounts. Labor and equipment rates may include overhead or selling rates; verify the cost basis before drawing margin conclusions.</p><p>Actual dollars come from job-cost records already in BidClaw. Hours come only from posted CrewClaw reviews and are not added again as dollar costs. Missing costs are not zero spending. This report does not measure final profit or percent complete.</p><p>The date limits actuals only. The selected budget is its current saved proposal snapshot, not a historical budget as of that date.</p></div>
 <div className="flex flex-wrap items-end gap-4"><label>Project<select className={field} value={project} onChange={e=>setProject(e.target.value)}><option value="">All projects</option>{data.projects.filter(p=>archived||p.status!=='archived').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Actuals through<input className={field} type="date" required value={asOf} onChange={e=>setAsOf(e.target.value||today())}/></label><label><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setProject('')}}/> Include archived</label><button className="rounded bg-brand-navy px-4 py-2 text-white disabled:opacity-50" disabled={loading||!!error||!reports.length} onClick={download}>Export Excel CSV</button></div>
 <nav aria-label="Report views" className="flex flex-wrap gap-3">{[['budget','Budget vs Actual'],['labor','Labor Hours'],['attention','Needs Attention']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)} className={`rounded border px-4 py-2 ${view===id?'bg-brand-navy text-white':'bg-white'}`}>{label}</button>)}</nav>
 {loading?<p role="status">Loading report data…</p>:error?<p role="alert">Couldn’t load the report: {error}. Refresh to retry.</p>:<>
 {view==='budget'&&<div className="overflow-x-auto rounded border bg-white"><table className="w-full min-w-[780px] text-sm"><thead><tr>{['Project / baseline','Budget cost basis','Recorded cost','Budget remaining','Cost data'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{reports.map(r=><tr key={r.project.id}><td className="border-t p-3"><Link className="font-bold underline" to={`/app/projects/${r.project.id}?tab=job_cost`}>{r.project.name}</Link><p>{r.proposal?.name??'No proposal'} · {r.provisional?'Provisional':'Approved baseline'}</p></td>{cell(r.proposal?formatUSD(r.budgetTotal):'—')}{cell(r.costCount?formatUSD(r.actualTotal):'Not recorded')}{cell(r.proposal&&r.costCount?formatUSD(r.budgetTotal-r.actualTotal):'—')}{cell(`${r.costCount} cost lines`)}</tr>)}</tbody></table></div>}
 {view==='labor'&&<div className="overflow-x-auto rounded border bg-white"><table className="w-full min-w-[680px] text-sm"><thead><tr>{['Project','Budget hours','Posted actual hours','Hours remaining','Budget used'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{reports.map(r=><tr key={r.project.id}>{cell(r.project.name)}{cell(r.budgetHours||'No hourly budget')}{cell(r.hourRecordCount?r.actualHours:'Not recorded')}{cell(r.hourRecordCount&&r.budgetHours?roundMoney(r.budgetHours-r.actualHours):'—')}{cell(r.hourRecordCount&&r.budgetHours?`${roundMoney(100*r.actualHours/r.budgetHours)}%`:'—')}</tr>)}</tbody></table><p className="p-3 text-sm">Budget usage is not productivity or percent complete. Only recognized hourly labor units are counted; crew days and lump sums need conversion before comparison.</p></div>}
 {view==='attention'&&<section className="space-y-3">{reports.map(r=><article className="rounded border bg-white p-4" key={r.project.id}><h2 className="font-bold">{r.project.name}</h2><ul className="list-disc pl-5">{flags(r).map((f,i)=><li key={i}>{f}</li>)}</ul>{!flags(r).length&&<p>No exceptions detected in recorded data.</p>}</article>)}<article className="rounded border bg-white p-4"><h2 className="font-bold">Unassigned costs — all projects</h2><p>{unassigned.length} lines · {formatUSD(unassigned.reduce((s,c)=>s+Number(c.amount),0))}. These are excluded from project actuals.</p>{unassigned.map(c=><p key={c.id}>{c.txn_date} · {c.vendor_name} · {c.description} · {formatUSD(Number(c.amount))}</p>)}</article></section>}
 {!reports.length&&<p>No projects match these filters.</p>}
 {reports.map(r=><details className="rounded border bg-white p-4" key={r.project.id} open={!!project}><summary className="cursor-pointer font-bold">{r.project.name} — category and work-area detail</summary><label className="mt-3 block">Budget proposal<select className={field} value={r.proposal?.id??''} onChange={e=>setBaselines({...baselines,[r.project.id]:e.target.value})}><option value="" disabled>No proposal</option>{data.proposals.filter(p=>p.project_id===r.project.id&&p.status!=='lost').map(p=><option key={p.id} value={p.id}>{p.name} ({p.status})</option>)}</select></label><p className="my-2 text-sm">Default: latest updated approved proposal, otherwise latest non-lost proposal marked provisional. Proposal versions are not added together.</p><div className="overflow-x-auto"><table className="min-w-[500px] w-full text-sm"><thead><tr><th className="p-3 text-left">Category</th><th>Budget</th><th>Recorded actual</th><th>Remaining</th></tr></thead><tbody>{categories.map(c=><tr key={c}>{cell(names[c])}{cell(r.proposal?formatUSD(r.budget[c]):'—')}{cell(r.costCount?formatUSD(r.actual[c]):'Not recorded')}{cell(r.proposal&&r.costCount?formatUSD(r.budget[c]-r.actual[c]):'—')}</tr>)}</tbody></table></div><h3 className="mt-3 font-bold">Work-area budgets</h3>{r.areas.map(a=><p key={a.id}>{a.name}: {formatUSD(a.budget)}</p>)}<p className="mt-2 text-sm">Actual costs and hours are recorded at project level. They have not been allocated to work areas.</p><Link className="mt-3 inline-block underline" to={`/app/projects/${r.project.id}?tab=job_cost`}>Open cost transactions</Link></details>)}
 </>}
 </div>
}
