import assert from 'node:assert/strict'
import {reportProject,reportCsv,type ReportData} from '../src/lib/jobReports'
const p={id:'j',name:'Test job',status:'in_progress'}
const d:ReportData={projects:[p],proposals:[{id:'approved',project_id:'j',name:'Approved',status:'approved',updated_at:'2026-01-01'},{id:'draft',project_id:'j',name:'Draft',status:'draft',updated_at:'2026-09-01'}],areas:[{id:'a',proposal_id:'approved',enabled:true,name_override:null,work_areas:{name:'Patio'}},{id:'off',proposal_id:'approved',enabled:false,name_override:null,work_areas:null}],lines:[{id:'l',proposal_id:'approved',proposal_work_area_id:'a',category:'labor',unit:'HR',quantity:10,frozen_unit_cost:50,frozen_markup_percent:100,price_override:9999},{id:'m',proposal_id:'approved',proposal_work_area_id:'off',category:'material',unit:'EA',quantity:10,frozen_unit_cost:10,frozen_markup_percent:0}],costs:[{id:'c',project_id:'j',category:'labor',amount:550,txn_date:'2026-09-01',description:'Labor',account_name:null,vendor_name:null},{id:'refund',project_id:'j',category:'labor',amount:-50,txn_date:'2026-09-02',description:'Credit',account_name:null,vendor_name:null},{id:'future',project_id:'j',category:'labor',amount:5000,txn_date:'2027-01-01',description:'Future',account_name:null,vendor_name:null},{id:'u',project_id:null,category:'labor',amount:300,txn_date:'2026-09-01',description:'Unassigned',account_name:null,vendor_name:null}],reviews:[{id:'r',project_id:'j',work_date:'2026-09-01',status:'posted',total_seconds:12*3600,extras:[{}],materials:[]},{id:'pending',project_id:'j',work_date:'2026-09-01',status:'needs_review',total_seconds:30*3600,extras:[],materials:[]}]}
const r=reportProject(d,p,'2026-09-14');assert.equal(r.proposal?.id,'approved');assert.equal(r.budgetTotal,500);assert.equal(r.actualTotal,500);assert.equal(r.budgetHours,10);assert.equal(r.actualHours,12);assert.equal(r.pending,1);assert.equal(r.costCount,2);assert.equal(r.areas.length,1);assert.equal(r.extras,1)
assert.equal(reportProject(d,p,'2026-09-14','draft').provisional,true)
const noActual=reportProject({...d,costs:[],reviews:[]},p,'2026-09-14');assert.equal(noActual.costCount,0);assert.equal(noActual.hourRecordCount,0)
assert.equal(reportProject({...d,proposals:[]},p,'2026-09-14').proposal,null)
assert.match(reportCsv([['=HYPERLINK("bad")',-3,null]]),/"'=HYPERLINK/)
assert.equal(reportProject({...d,lines:[{...d.lines[0],unit:'DAY'}]},p,'2026-09-14').nonHourLabor,1)
console.log('Job report checks passed: approved baseline, exclusions, cost/price separation, credits, cutoff, unassigned costs, posted-only hours, missing data and CSV safety.')
